# Configuration for Alacritty

import:
  - ~/.config/alacritty/colors.yml
  - ~/.config/alacritty/fonts.yml

env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 130
    lines: 30

  padding:
    x: 10
    y: 10

  decorations: none

  opacity: 1.0

  startup_mode: Maximized

  class:
    instance: Alacritty
    general: Alacritty

scrolling:
  history: 10000

  multiplier: 3

draw_bold_text_with_bright_colors: true

cursor:
  # Cursor style
  style:
    # Cursor shape
    #
    # Values for `shape`:
    #   - ▇ Block
    #   - _ Underline
    #   - | Beam
    shape: Block

  blinking: on

  blink_interval: 750

live_config_reload: true
